
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

shell_command:
  "off": "curl https://android-tv.home.ihanastudio.com/off"
  "on": "curl https://android-tv.home.ihanastudio.com/on"
  idle: "curl https://android-tv.home.ihanastudio.com/idle"
  onoff: "curl https://android-tv.home.ihanastudio.com/onoff"
  paused: "curl https://android-tv.home.ihanastudio.com/paused"
  playing: "curl https://android-tv.home.ihanastudio.com/playing"