---
releases:
  - name: android-tv
    chart: ./chart/android-tv
    namespace: android-tv
    values:
      - image:
          registry: 192.168.1.117:30500
          repository: android-tv
          tag: latest
          pullPolicy: IfNotPresent
        internalRegistry:
          enabled: true
          nodePort: 30500
