DNS1:
  192.168.1.1
doh:
  pullPolicy: IfNotPresent
image:
  pullPolicy: IfNotPresent
ingress:
  enabled: true
  hosts:
    - "pihole.home"
monitoring:
  sidecar:
    image:
      pullPolicy: IfNotPresent
persistentVolumeClaim:
  enabled: true
serviceDns:
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  loadBalancerIP: 192.168.1.250
  type: LoadBalancer
serviceWeb:
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  loadBalancerIP: 192.168.1.250
  type: LoadBalancer