apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
  annotations:
    meta.helm.sh/release-name: cert-manager-cloudflare-token
    meta.helm.sh/release-namespace: cert-manager
  labels:
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  api-token: {{ .Values.cloudflare_token | b64enc | quote }}
