apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: internal-registry-data
  labels:
    app.kubernetes.io/name: internal-registry
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
