---
apiVersion: v1
kind: ConfigMap
metadata:
  name: android
data:
{{ (.Files.Glob ".android/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: src
data:
{{- range $path, $_ := .Files.Glob "src/**" }}
{{- if and (not (hasSuffix "/" $path)) (regexMatch "\\.(py|sh|html)$" $path) }}
  {{ $path | trimPrefix "src/" | replace "/" "_" }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- end }}
