---
apiVersion: v1
kind: ConfigMap
metadata:
  name: android
data:
{{ (.Files.Glob ".android/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: src
data:
{{ (.Files.Glob "deno/src/*").AsConfig | indent 2 }}
{{ (.Files.Glob "deno/*").AsConfig | indent 2 }}