apiVersion: v1
kind: Service
metadata:
  name: android-rpi
spec:
  type: NodePort
  selector:
    app: android-rpi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: {{ .Values.service.rpiNodePort }}
