apiVersion: apps/v1
kind: Deployment
metadata:
  name: android-tv
spec:
  selector:
    matchLabels:
      app: android-tv
  template:
    metadata:
      labels:
        app: android-tv
    spec:
      hostNetwork: true
      containers:
        - name: adb
          image: qimat/android-tv:20250720
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          command:
            - deno
            - run
            - -A
            - main.ts
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          securityContext:
            privileged: true
          volumeMounts:
            - name: android
              mountPath: /root/.android
            - name: src
              mountPath: /src
          workingDir: /src
          startupProbe:
            exec:
              command:
                - adb
                - connect
                - 192.168.1.112
          livenessProbe:
            exec:
              command:
                - adb
                - connect
                - 192.168.1.112
      volumes:
        - name: android
          configMap:
            name: android
        - name: src
          configMap:
            name: src
