apiVersion: v1
kind: Secret
metadata:
  name: tunnel-credentials
  namespace: cloudflare-tunnel
  annotations:
    meta.helm.sh/release-name: cloudflare-tunnel
    meta.helm.sh/release-namespace: cloudflare-tunnel
type: Opaque
data:
  credentials.json: {{ .Values.credentialsJson | toJson | b64enc | quote }}
