---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool
  namespace: metallb-system
  annotations:
    meta.helm.sh/release-name: metallb-ip-range
    meta.helm.sh/release-namespace: metallb-system
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  addresses:
    - 192.168.1.200-192.168.1.250