ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  hosts:
    - host: ha.home.ihanastudio.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
      - ha.home.ihanastudio.com
      secretName: home-assistant

configuration:
  enabled: true
  forceInit: true
  trusted_proxies:
    - 10.42.0.0/16
  templateConfig: |-
    # Loads default set of integrations. Do not remove.
    default_config:

    {{- if .Values.ingress.enabled }}
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        {{- range .Values.configuration.trusted_proxies }}
        - {{ . }}
        {{- end }}
    {{- end}}
    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml
