dnsConfig:
  nameservers:
    - 192.168.1.250
  searches:
    - android-tv.home.ihanastudio.com
dnsPolicy: None
hostNetwork: true
ingress:
  enabled: true
persistence:
  enabled: true
configuration:
  enabled: true
  forceInit: true
  templateConfig: |-
    # Loads default set of integrations. Do not remove.
    default_config:

    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml

    shell_command:
      "off": "curl https://android-tv.home.ihanastudio.com/off"
      "on": "curl https://android-tv.home.ihanastudio.com/on"
      buffering: "curl https://android-tv.home.ihanastudio.com/buffering"
      idle: "curl https://android-tv.home.ihanastudio.com/idle"
      onoff: "curl https://android-tv.home.ihanastudio.com/onoff"
      paused: "curl https://android-tv.home.ihanastudio.com/paused"
      playing: "curl https://android-tv.home.ihanastudio.com/playing"