apiVersion: v1
kind: Service
metadata:
  name: local-llm-ui
spec:
  type: NodePort
  selector:
    app: local-llm-ui
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30083
