hostname: rancher.home.ihanastudio.com
ingress:
  tls:
    source: secret
  extraAnnotations:
    cert-manager.io/cluster-issuer: cloudflare-clusterissuer
  ingressClassName: nginx
replicas: 2
letsEncrypt:
  email: qiqi2k7@hotmail.com
  ingress:
    class: nginx
