extraArgs:
  pihole-api-version: 6
extraEnvVars:
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: pihole-password
image:
  pullPolicy: IfNotPresent
pihole:
  server: http://pihole-web.pihole-system.svc.cluster.local
provider: pihole