provider: pihole
pihole:
  server: http://pihole-web.pihole-system.svc.cluster.local
extraEnvVars:
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pihole-password
        key: password
